name: Install Python with uv
description: |
  This GitHub Action installs Python using the uv tool.
  It caches uv files, and installs dependencies.

inputs:
  use_openvino:
    description: "openvino extra をインストールする場合は true"
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: Extract Python Version
      run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      shell: bash

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      shell: bash
      run: |
        set -e
        if [ "${{ inputs.use_openvino }}" = "true" ]; then
          echo "[info] uv sync --frozen --extra openvino"
          uv sync --frozen --extra openvino
        else
          echo "[info] uv sync --frozen"
          uv sync --frozen
        fi