[project]
name = "sigotodekirukun"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "alembic>=1.16.2",
    "flet==0.27.6",
    "langchain>=0.3.25",
    "langchain-google-genai>=2.1.5",
    "langgraph>=0.4.8",
    "langgraph-checkpoint-sqlite>=2.0.10",
    "langsmith>=0.3.45",
    "loguru>=0.7.3",
    "python-dotenv>=1.1.0",
    "sqlmodel>=0.0.24",
]

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.mycompany"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "sigotodekirukun"

# company name to display in about app dialogs
company = "Flet"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Flet"

[tool.flet.app]
path = "src"

[tool.uv]
dev-dependencies = [
    "flet[all]==0.27.6",
    "pre-commit>=4.2.0",
    "pyright>=1.1.400",
    "pytest>=8.4.0",
    "ruff>=0.11.0, <0.12",
]

# (https://zenn.dev/mutex_inc/articles/4183b992ccd701)
[tool.ruff]
line-length = 120
exclude = [
    "src/models/migrations/versions/",
]

[tool.ruff.format]
docstring-code-format = true


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D1",    # undocumented
    "D203",  # one blank line before class
    "D213",  # multi-line summary second line
    "D400",
    "D415",
    "TD001", # invalid todo tag
    "TD002", # missing todo author
    "TD003", # missing todo link
    "PD011", # pandas use of dot values
    "ERA001",
    "RUF001",
    "RUF002",
    "RUF003",
    "COM812",
    "DTZ005",
    "BLE001",
]
unfixable = [
    "F401", # unused import
    "F841", # unused variable
]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "D",
    "S101",
    "N802",
    "ARG",
]

# logger-objects = ["src.library.logger.LOGGER"]

[tool.ruff.lint.pylint]
max-args = 6


[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs",
    "src/models/migrations/versions"
]
typeCheckingMode = "basic"
venvPath = "."
venv = ".venv"


[tool.pytest.ini_options]
pythonpath = "src"

testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

addopts = [
    "--strict-markers",
    "--disable-warnings",
    "--verbose",
]

markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "unit: marks tests as unit tests",
    "integration: marks tests as integration tests",
]
