"""add terminology management tables

Revision ID: 4c9717c0dda8
Revises: 0c67461da58a
Create Date: 2025-10-21 14:44:28.276478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c9717c0dda8'
down_revision: Union[str, Sequence[str], None] = '0c67461da58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'DEPRECATED', name='termstatus'), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_key'), 'terms', ['key'], unique=True)
    op.create_index(op.f('ix_terms_status'), 'terms', ['status'], unique=False)
    op.create_table('synonyms',
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_term_id'), 'synonyms', ['term_id'], unique=False)
    op.create_index(op.f('ix_synonyms_text'), 'synonyms', ['text'], unique=False)
    op.create_table('term_tag',
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('term_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_tag')
    op.drop_index(op.f('ix_synonyms_text'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_term_id'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index(op.f('ix_terms_status'), table_name='terms')
    op.drop_index(op.f('ix_terms_key'), table_name='terms')
    op.drop_table('terms')
    # ### end Alembic commands ###
