name: Assign Label
on:
  pull_request:
    types: [opened, reopened, synchronize]
  issues:
    types: [opened, reopened]
jobs:
  assign-label:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler_branch.yml