name: Check Docs

on:
  pull_request:
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs*.yml"
      - "pyproject.toml"

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Build docs (strict mode)
        run: uv run mkdocs build --strict
        env:
          MKDOCS_GIT_COMMITTERS_ENABLED: false

      - name: Check for broken links (basic)
        run: |
          # Basic check for obviously broken internal links
          find site -name "*.html" -exec grep -l "href=\"#\"" {} \; || true
          find site -name "*.html" -exec grep -l "src=\"\"" {} \; || true