name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
      - "pyproject.toml"
      - "uv.lock"
      - "scripts/generate_env_docs.py"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Run Scripts # generate env docs
        run: uv run python -m scripts.generate_env_docs

      - name: Build site
        run: uv run mkdocs build
        env:
          MKDOCS_GIT_COMMITTERS_ENABLED: false

      - name: Check for broken links
        run: |
          # Basic check for obviously broken internal links
          find site -name "*.html" -exec grep -l "href=\"#\"" {} \; || true
          find site -name "*.html" -exec grep -l "src=\"\"" {} \; || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
