name: Lint

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/lint.yml"
      - "**.py"
      - ".python-version"
      - "pyproject.toml"
      - "pyrightconfig.json"
      - "ruff.toml"
      - "uv.lock"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/lint.yml"
      - "**.py"
      - ".python-version"
      - "pyproject.toml"
      - "pyrightconfig.json"
      - "ruff.toml"
      - "uv.lock"

  workflow_dispatch:
  workflow_call:

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by Pyright
        run: uv run pyright

  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by Ruff
        run: uv run ruff check --fix src tests
